// Copyright (c) 2015 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(n){var f,b={_breaker:{},_start:null,each:function(){var a,c=function(c,e){return c===b._breaker||e&&b.elapsed()>a};return function(d,e,g){var q,k;k=b.type(d);if(1===arguments.length)a=arguments[0];else if(g=b.extend({timeout:!1},g),"object"===k&&d.hasOwnProperty)for(q in d){if(d.hasOwnProperty(q)&&c(e(d[q],q),g.timeout))break}else if(d){q=0;for(k=d.length;q<k&&!c(e(d[q],q),g.timeout);q++);}}}(),extend:function(a){var c,b,e,g,q=arguments.length;a=a||{};for(b=1;b<q;b++)if(g=arguments[b],void 0!==
g&&null!==g)for(e in g)c=g[e],a!==c&&void 0!==c&&(a[e]=c);return a},noop:function(){},type:function(){var a=function(a,b){try{return("function"===typeof window[b]||"object"===typeof window[b])&&a instanceof window[b]}catch(e){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?
"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var d="array"===b.type(a)?[]:{};b.each(a,function(a,g){c(a,g)&&("array"===b.type(d)?d.push(a):d[g]=a)});return d},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,b){return(c=a[c])&&c.split?c.split(b||" "):[]},batchable:function(a,c){c=c||b.noop;
var d=function(){return b.extend({batch:!0,timeout:100},c())},e=b.traits.cors&&b.traits.json,g=[],q=null,k=function(){null!==q&&(clearTimeout(q),q=null);1===g.length?a.apply(null,g[0].arguments):1<g.length&&a.apply(null,g);g=[]},f=function(){g.push({arguments:b.toArray(arguments),batch:!0});!e||!d().batch?k():null===q&&(q=setTimeout(b.entryPoint(b.bind(function(){k()},this)),d().timeout))};b.extend(f,{flush:k,now:a});return f},batchArgs:function(a,c){return b.map(a,function(a){return void 0===c?a.arguments:
a.arguments[c]})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(a){return"object"===b.type(a)&&a.batch&&"array"===b.type(a.arguments)}).length===a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(e,g,f){if(e){var k=e[c];if(k||void 0!==f)return k||(k=++b),a[k]||(e[c]=k,a[k]={}),void 0!==f&&(a[k][g]=f),"string"===typeof g?a[k][g]:a[k]}}}(),canonicalizeHostname:function(a){"string"===
typeof a&&(a=b.createA(a));try{return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""}catch(c){return""}},clone:function(a){return b.extend({},a)},contains:function(a,c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,
b===c)return!0;return!1},cors:function(a,c,b){var e,g=function(){b?b(e.responseText):eval(e.responseText)};e=new window.XMLHttpRequest;e.onreadystatechange=function(){4===e.readyState&&200===e.status&&g()};try{return e.open("POST",a),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),e.withCredentials=!0,e.send(c),!0}catch(f){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,e){var g;a=(e||document).createElement(a);c=c||{};d=d||
{};for(g in c)void 0!==c[g]&&(a[g]=c[g]);b.css(a,d);return a},css:function(a,c){for(var b in c)try{a.style[b]=c[b]}catch(e){}return a},destructing:function(a){return function(a){var b=!1,e;return function(){b||(e=a.apply(null,arguments),b=!0);return e}}(a)},elapsed:function(){return this._start?(new Date).getTime()-this._start.getTime():0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},
escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(e){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,e){if(void 0!==e)a=e,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(e){c(e)}else return b.apply(this,arguments)}}}(),find:function(a,
c,d){var e;b.each(a,function(a,d){if(c(a,d))return e=a,b._breaker},d);return e},generateNodeFilter:function(){var a=function(a,b){var g,f;b=","+b.join(",")+",";g=0;for(f=a.length;g<f;g++)if(c(a[g],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,g){g=b.extend({ancestors:!0,self:!0},g);var f=function(e,g){var f;if(f=!(d.tags.length&&
c(e.nodeName.toLowerCase(),d.tags))){if(f=d.classes.length){f=d.classes;var q=b.attrValues(e,"className");f=a(f,q)}if(f=!f){if(f=d.rels.length)f=d.rels,q=b.attrValues(e,"rel"),f=c(e.nodeName.toLowerCase(),",a,")&&a(f,q);f=!f&&!("function"===b.type(d.custom)&&d.custom(e,g))}}return f};if(g.self&&!f(e,!0))return!1;if(g.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!f(e,!1))return!1;return!0}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},fromQuery:function(a){"?"===
a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,e=Infinity,g=-Infinity,f=-Infinity,k;for(a=0;a<c;a++)k=b.position(arguments[a]),d=Math.min(d,k.x),e=Math.min(e,k.y),g=Math.max(g,k.x+arguments[a].offsetWidth),f=Math.max(f,k.y+arguments[a].offsetHeight);return{x:d,y:e,w:g-d,h:f-e,x1:d,y1:e,x2:g,y2:f}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,d,e){return c?b.contains(b.attrValues(a,c,e),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];
a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c,d){return b.reduce([],a,function(a,b,d){a.push(c(b,d));return a},d)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(d){return!0}},nodesOfType:function(a){var c=b.toArray(arguments).slice(1);return b.all(a,function(a){return b.contains(c,a.nodeType)})},on:function(){var a;return function(c,d,e){var g,f,k;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;e=d;d=c;c=a}else g=b.toArray(arguments).slice(3,arguments.length);try{f=c["on"+d]}catch(m){}"function"===typeof f&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=f.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));k=b.entryPoint(function(){if(a.enabled())return e.apply(null,b.toArray(arguments).concat(g||
[]))});c.addEventListener?c.addEventListener(d,k,!1):c.attachEvent&&c.attachEvent("on"+d,k)}}}(),position:function(a,c){var d,e=0,g=0,f=0,k=0;c=c||document;if(!b.isInDom(a))return!1;d=a;do e+=d.offsetLeft,g+=d.offsetTop,d=d.offsetParent;while(d);d=a;do f+=d.scrollLeft,k+=d.scrollTop,d=d.parentNode;while(d&&d!==c.body);return{x:e-f,y:g-k}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});
return a},ready:function(){var a=!1,c=[],d=!1,e,g,f,k,m;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,!1);m()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),m())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return m();if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
k);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&g()}b.on(window,"load",m)}};g=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(g),1);return}m()}};m=function(){if(!d){if(!document.body)return setTimeout(b.entryPoint(m),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){e();d?a():c.push(a)}}(),reduce:function(a,c,d,e){b.each(c,function(c,b){a=d(a,c,b)},e);return a},reformatKeys:function(a){var c,
d,e=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,e),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,e,g=b.attrValues(a,"className");d=0;for(e=g.length;d<e;d++)g[d]===c&&delete g[d];a.className=g.join(" ")}},request:function(a,c,d){var e,g,f,k=b.uniqid("vglnk_"),m=b.toArray(arguments).slice(3,arguments.length),h=function(a,c,d){var e=b.createA(a).protocol;c.length&&(a=b.updateUrl(a,
{search:"?"+c}));if(!0===d||!1===d)a=b.updateUrl(a,{protocol:e.replace(/s?:$/,function(){return d?"s:":":"})});return a};d=b.extend({fn:b.noop,jsonp:!0,"return":!1,ssl:null,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],k=d.fn):"function"===typeof d.fn&&(e=d.fn);"function"===b.type(e)&&(f=b.entryPoint(b.destructing(function(){e.apply(this,b.toArray(arguments).concat(m));window[k]&&(window[k]=void 0)})),null!==d.timeout&&setTimeout(f,d.timeout));!0===d.jsonp&&(window[k]=f,c=b.extend({format:"jsonp",
jsonp:k},c));g=b.toQuery(c);return d["return"]?h(a,g,d.ssl):b.traits.cors&&b.cors(h(a,"",d.ssl),g,d.jsonp?null:f)?!0:b.jsonp(h(a,g,d.ssl))},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},stopPropagation:function(a){a&&a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,e,g=[];b=0;for(e=a.length;b<e;b++)g[b]=a[b];return g}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},
toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,d){b.contains(a,d)||a.push(d);return a})},withScope:function(){var a=function(a,d,e){if(e.self&&b.contains(d,a))return a;if(e.ancestors)return b.find(b.ancestors(a).slice(0),
function(a){return b.contains(d,a)},{timeout:!0})};return function(c,d,e){var g=b.select(d);e=b.extend({ancestors:!0,consolidate:!1,descendants:!0,self:!0},e);c=b.all(b.map(c,function(c){var d,f=[];(d=a(c,g,e))?f.push(d):1===c.nodeType&&e.descendants&&b.each(g,function(a){b.contains(b.ancestors(a),c)&&f.push(a)},{timeout:!0});return[c,f]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return e.consolidate?b.reduce([],c,function(a,c){return a.concat(c[1])}):c}}()});var s=function(){var a=
b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};s.amd=!0;(function(a){function c(a,c,b,d){var e,g,f,k,m;(c?c.ownerDocument||c:B)!==z&&I(c);c=c||z;b=b||[];if(!a||"string"!==typeof a)return b;if(1!==(k=c.nodeType)&&9!==k)return[];if(D&&!d){if(e=sa.exec(a))if(f=e[1])if(9===k)if((g=c.getElementById(f))&&g.parentNode){if(g.id===f)return b.push(g),b}else return b;else{if(c.ownerDocument&&(g=c.ownerDocument.getElementById(f))&&S(c,g)&&g.id===f)return b.push(g),b}else{if(e[2])return J.apply(b,
c.getElementsByTagName(a)),b;if((f=e[3])&&x.getElementsByClassName&&c.getElementsByClassName)return J.apply(b,c.getElementsByClassName(f)),b}if(x.qsa&&(!A||!A.test(a))){g=e=y;f=c;m=9===k&&a;if(1===k&&"object"!==c.nodeName.toLowerCase()){k=T(a);(e=c.getAttribute("id"))?g=e.replace(ta,"\\$&"):c.setAttribute("id",g);g="[id='"+g+"'] ";for(f=k.length;f--;)k[f]=g+p(k[f]);f=da.test(a)&&l(c.parentNode)||c;m=k.join(",")}if(m)try{return J.apply(b,f.querySelectorAll(m)),b}catch(h){}finally{e||c.removeAttribute("id")}}}return ja(a.replace(Y,
"$1"),c,b,d)}function b(){function a(b,d){c.push(b+" ")>t.cacheLength&&delete a[c.shift()];return a[b+" "]=d}var c=[];return a}function e(a){a[y]=!0;return a}function g(a){var c=z.createElement("div");try{return!!a(c)}catch(b){return!1}finally{c.parentNode&&c.parentNode.removeChild(c)}}function f(a,c){for(var b=a.split("|"),d=a.length;d--;)t.attrHandle[b[d]]=c}function k(a,c){var b=c&&a,d=b&&1===a.nodeType&&1===c.nodeType&&(~c.sourceIndex||ka)-(~a.sourceIndex||ka);if(d)return d;if(b)for(;b=b.nextSibling;)if(b===
c)return-1;return a?1:-1}function m(a){return function(c){return"input"===c.nodeName.toLowerCase()&&c.type===a}}function h(a){return function(c){var b=c.nodeName.toLowerCase();return("input"===b||"button"===b)&&c.type===a}}function w(a){return e(function(c){c=+c;return e(function(b,d){for(var e,g=a([],b.length,c),f=g.length;f--;)if(b[e=g[f]])b[e]=!(d[e]=b[e])})})}function l(a){return a&&typeof a.getElementsByTagName!==O&&a}function r(){}function p(a){for(var c=0,b=a.length,d="";c<b;c++)d+=a[c].value;
return d}function n(a,c,b){var d=c.dir,e=b&&"parentNode"===d,g=ua++;return c.first?function(c,b,g){for(;c=c[d];)if(1===c.nodeType||e)return a(c,b,g)}:function(c,b,f){var X,ca,k=[C,g];if(f)for(;c=c[d];){if((1===c.nodeType||e)&&a(c,b,f))return!0}else for(;c=c[d];)if(1===c.nodeType||e){ca=c[y]||(c[y]={});if((X=ca[d])&&X[0]===C&&X[1]===g)return k[2]=X[2];ca[d]=k;if(k[2]=a(c,b,f))return!0}}}function H(a){return 1<a.length?function(c,b,d){for(var e=a.length;e--;)if(!a[e](c,b,d))return!1;return!0}:a[0]}
function P(a,c,b,d,e){for(var g,f=[],k=0,m=a.length,h=null!=c;k<m;k++)if(g=a[k])if(!b||b(g,d,e))f.push(g),h&&c.push(k);return f}function U(a,b,d,g,f,k){g&&!g[y]&&(g=U(g));f&&!f[y]&&(f=U(f,k));return e(function(e,k,m,h){var q,u,w=[],l=[],r=k.length,v;if(!(v=e)){v=b||"*";for(var p=m.nodeType?[m]:m,ia=[],n=0,t=p.length;n<t;n++)c(v,p[n],ia);v=ia}v=a&&(e||!b)?P(v,w,a,m,h):v;p=d?f||(e?a:r||g)?[]:k:v;d&&d(v,p,m,h);if(g){q=P(p,l);g(q,[],m,h);for(m=q.length;m--;)if(u=q[m])p[l[m]]=!(v[l[m]]=u)}if(e){if(f||
a){if(f){q=[];for(m=p.length;m--;)if(u=p[m])q.push(v[m]=u);f(null,p=[],q,h)}for(m=p.length;m--;)if((u=p[m])&&-1<(q=f?M.call(e,u):w[m]))e[q]=!(k[q]=u)}}else p=P(p===k?p.splice(r,p.length):p),f?f(null,k,p,h):J.apply(k,p)})}function ea(a){var c,b,d,e=a.length,f=t.relative[a[0].type];b=f||t.relative[" "];for(var g=f?1:0,k=n(function(a){return a===c},b,!0),m=n(function(a){return-1<M.call(c,a)},b,!0),q=[function(a,b,d){return!f&&(d||b!==Z)||((c=b).nodeType?k(a,b,d):m(a,b,d))}];g<e;g++)if(b=t.relative[a[g].type])q=
[n(H(q),b)];else{b=t.filter[a[g].type].apply(null,a[g].matches);if(b[y]){for(d=++g;d<e&&!t.relative[a[d].type];d++);return U(1<g&&H(q),1<g&&p(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(Y,"$1"),b,g<d&&ea(a.slice(g,d)),d<e&&ea(a=a.slice(d)),d<e&&p(a))}q.push(b)}return H(q)}function va(a,b){var d=0<b.length,g=0<a.length,f=function(e,f,k,m,q){var h,u,p,w=0,l="0",v=e&&[],r=[],ha=Z,n=e||g&&t.find.TAG("*",q),la=C+=null==ha?1:Math.random()||0.1,ra=n.length;for(q&&(Z=f!==z&&f);l!==ra&&
null!=(h=n[l]);l++){if(g&&h){for(u=0;p=a[u++];)if(p(h,f,k)){m.push(h);break}q&&(C=la)}d&&((h=!p&&h)&&w--,e&&v.push(h))}w+=l;if(d&&l!==w){for(u=0;p=b[u++];)p(v,r,f,k);if(e){if(0<w)for(;l--;)!v[l]&&!r[l]&&(r[l]=wa.call(m));r=P(r)}J.apply(m,r);q&&(!e&&0<r.length&&1<w+b.length)&&c.uniqueSort(m)}q&&(C=la,Z=ha);return v};return d?e(f):f}var Q,x,t,$,ma,T,fa,ja,Z,K,R,I,z,E,D,A,N,aa,S,y="sizzle"+-new Date,B=a.document,C=0,ua=0,na=b(),oa=b(),pa=b(),ga=function(a,c){a===c&&(R=!0);return 0},O="undefined",ka=
-2147483648,xa={}.hasOwnProperty,L=[],wa=L.pop,ya=L.push,J=L.push,qa=L.slice,M=L.indexOf||function(a){for(var c=0,b=this.length;c<b;c++)if(this[c]===a)return c;return-1},Y=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,za=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Aa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ba=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ca=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Da=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ba={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ea=/^(?:input|select|textarea|button)$/i,Fa=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,sa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,ta=/'|\\/g,F=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,G=function(a,c,b){a="0x"+c-65536;return a!==a||b?c:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{J.apply(L=qa.call(B.childNodes),B.childNodes),L[B.childNodes.length].nodeType}catch(Ga){J={apply:L.length?function(a,c){ya.apply(a,qa.call(c))}:function(a,c){for(var b=
a.length,d=0;a[b++]=c[d++];);a.length=b-1}}}x=c.support={};ma=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};I=c.setDocument=function(a){var c=a?a.ownerDocument||a:B;a=c.defaultView;if(c===z||9!==c.nodeType||!c.documentElement)return z;z=c;E=c.documentElement;D=!ma(c);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){I()},!1):a.attachEvent&&a.attachEvent("onunload",function(){I()}));x.attributes=g(function(a){a.className="i";return!a.getAttribute("className")});
x.getElementsByTagName=g(function(a){a.appendChild(c.createComment(""));return!a.getElementsByTagName("*").length});x.getElementsByClassName=V.test(c.getElementsByClassName)&&g(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});x.getById=g(function(a){E.appendChild(a).id=y;return!c.getElementsByName||!c.getElementsByName(y).length});x.getById?(t.find.ID=function(a,c){if(typeof c.getElementById!==O&&D){var b=
c.getElementById(a);return b&&b.parentNode?[b]:[]}},t.filter.ID=function(a){var c=a.replace(F,G);return function(a){return a.getAttribute("id")===c}}):(delete t.find.ID,t.filter.ID=function(a){var c=a.replace(F,G);return function(a){return(a=typeof a.getAttributeNode!==O&&a.getAttributeNode("id"))&&a.value===c}});t.find.TAG=x.getElementsByTagName?function(a,c){if(typeof c.getElementsByTagName!==O)return c.getElementsByTagName(a)}:function(a,c){var b,d=[],e=0,g=c.getElementsByTagName(a);if("*"===a){for(;b=
g[e++];)1===b.nodeType&&d.push(b);return d}return g};t.find.CLASS=x.getElementsByClassName&&function(a,c){if(typeof c.getElementsByClassName!==O&&D)return c.getElementsByClassName(a)};N=[];A=[];if(x.qsa=V.test(c.querySelectorAll))g(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),g(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(x.matchesSelector=V.test(aa=E.matches||E.webkitMatchesSelector||E.mozMatchesSelector||E.oMatchesSelector||E.msMatchesSelector))&&
g(function(a){x.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");N.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));N=N.length&&RegExp(N.join("|"));
S=(a=V.test(E.compareDocumentPosition))||V.test(E.contains)?function(a,c){var b=9===a.nodeType?a.documentElement:a,d=c&&c.parentNode;return a===d||!(!d||!(1===d.nodeType&&(b.contains?b.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,c){if(c)for(;c=c.parentNode;)if(c===a)return!0;return!1};ga=a?function(a,b){if(a===b)return R=!0,0;var d=!a.compareDocumentPosition-!b.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):
1;return d&1||!x.sortDetached&&b.compareDocumentPosition(a)===d?a===c||a.ownerDocument===B&&S(B,a)?-1:b===c||b.ownerDocument===B&&S(B,b)?1:K?M.call(K,a)-M.call(K,b):0:d&4?-1:1}:function(a,b){if(a===b)return R=!0,0;var d,e=0;d=a.parentNode;var g=b.parentNode,f=[a],W=[b];if(!d||!g)return a===c?-1:b===c?1:d?-1:g?1:K?M.call(K,a)-M.call(K,b):0;if(d===g)return k(a,b);for(d=a;d=d.parentNode;)f.unshift(d);for(d=b;d=d.parentNode;)W.unshift(d);for(;f[e]===W[e];)e++;return e?k(f[e],W[e]):f[e]===B?-1:W[e]===
B?1:0};return c};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==z&&I(a);b=b.replace(Ba,"='$1']");if(x.matchesSelector&&D&&(!N||!N.test(b))&&(!A||!A.test(b)))try{var d=aa.call(a,b);if(d||x.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(e){}return 0<c(b,z,null,[a]).length};c.contains=function(a,c){(a.ownerDocument||a)!==z&&I(a);return S(a,c)};c.attr=function(a,c){(a.ownerDocument||a)!==z&&I(a);var b=t.attrHandle[c.toLowerCase()],
b=b&&xa.call(t.attrHandle,c.toLowerCase())?b(a,c,!D):void 0;return void 0!==b?b:x.attributes||!D?a.getAttribute(c):(b=a.getAttributeNode(c))&&b.specified?b.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var c,b=[],d=0,e=0;R=!x.detectDuplicates;K=!x.sortStable&&a.slice(0);a.sort(ga);if(R){for(;c=a[e++];)c===a[e]&&(d=b.push(e));for(;d--;)a.splice(b[d],1)}K=null;return a};$=c.getText=function(a){var c,b="",d=0;if(c=a.nodeType)if(1===
c||9===c||11===c){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=$(a)}else{if(3===c||4===c)return a.nodeValue}else for(;c=a[d++];)b+=$(c);return b};t=c.selectors={cacheLength:50,createPseudo:e,match:ba,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(F,G);a[3]=(a[3]||a[4]||a[5]||"").replace(F,G);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var c,b=!a[6]&&a[2];if(ba.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(b&&Ca.test(b)&&(c=T(b,!0))&&(c=b.indexOf(")",b.length-c)-b.length))a[0]=a[0].slice(0,c),a[2]=b.slice(0,c);return a.slice(0,3)}},filter:{TAG:function(a){var c=
a.replace(F,G).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===c}},CLASS:function(a){var c=na[a+" "];return c||(c=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&na(a,function(a){return c.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==O&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(e){e=c.attr(e,a);if(null==e)return"!="===b;if(!b)return!0;e+="";return"="===b?e===d:"!="===b?
e!==d:"^="===b?d&&0===e.indexOf(d):"*="===b?d&&-1<e.indexOf(d):"$="===b?d&&e.slice(-d.length)===d:"~="===b?-1<(" "+e+" ").indexOf(d):"|="===b?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,c,b,d,e){var g="nth"!==a.slice(0,3),f="last"!==a.slice(-4),k="of-type"===c;return 1===d&&0===e?function(a){return!!a.parentNode}:function(c,b,m){var q,h,u,l,p;b=g!==f?"nextSibling":"previousSibling";var w=c.parentNode,v=k&&c.nodeName.toLowerCase();m=!m&&!k;if(w){if(g){for(;b;){for(h=c;h=h[b];)if(k?h.nodeName.toLowerCase()===
v:1===h.nodeType)return!1;p=b="only"===a&&!p&&"nextSibling"}return!0}p=[f?w.firstChild:w.lastChild];if(f&&m){m=w[y]||(w[y]={});q=m[a]||[];l=q[0]===C&&q[1];u=q[0]===C&&q[2];for(h=l&&w.childNodes[l];h=++l&&h&&h[b]||(u=l=0)||p.pop();)if(1===h.nodeType&&++u&&h===c){m[a]=[C,l,u];break}}else if(m&&(q=(c[y]||(c[y]={}))[a])&&q[0]===C)u=q[1];else for(;h=++l&&h&&h[b]||(u=l=0)||p.pop();)if((k?h.nodeName.toLowerCase()===v:1===h.nodeType)&&++u)if(m&&((h[y]||(h[y]={}))[a]=[C,u]),h===c)break;u-=e;return u===d||
0===u%d&&0<=u/d}}},PSEUDO:function(a,b){var d,g=t.pseudos[a]||t.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return g[y]?g(b):1<g.length?(d=[a,a,"",b],t.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,c){for(var d,e=g(a,b),f=e.length;f--;)d=M.call(a,e[f]),a[d]=!(c[d]=e[f])}):function(a){return g(a,0,d)}):g}},pseudos:{not:e(function(a){var c=[],b=[],d=fa(a.replace(Y,"$1"));return d[y]?e(function(a,c,b,e){e=d(a,null,e,[]);for(var g=a.length;g--;)if(b=e[g])a[g]=!(c[g]=b)}):
function(a,e,g){c[0]=a;d(c,null,g,b);return!b.pop()}}),has:e(function(a){return function(b){return 0<c(a,b).length}}),contains:e(function(a){a=a.replace(F,G);return function(c){return-1<(c.textContent||c.innerText||$(c)).indexOf(a)}}),lang:e(function(a){Da.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(F,G).toLowerCase();return function(c){var b;do if(b=D?c.lang:c.getAttribute("xml:lang")||c.getAttribute("lang"))return b=b.toLowerCase(),b===a||0===b.indexOf(a+"-");while((c=c.parentNode)&&
1===c.nodeType);return!1}}),target:function(c){var b=a.location&&a.location.hash;return b&&b.slice(1)===c.id},root:function(a){return a===E},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&!!a.checked||"option"===c&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Fa.test(a.nodeName)},input:function(a){return Ea.test(a.nodeName)},button:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&"button"===a.type||"button"===c},text:function(a){var c;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(c=a.getAttribute("type"))||"text"===c.toLowerCase())},first:w(function(){return[0]}),
last:w(function(a,c){return[c-1]}),eq:w(function(a,c,b){return[0>b?b+c:b]}),even:w(function(a,c){for(var b=0;b<c;b+=2)a.push(b);return a}),odd:w(function(a,c){for(var b=1;b<c;b+=2)a.push(b);return a}),lt:w(function(a,c,b){for(c=0>b?b+c:b;0<=--c;)a.push(c);return a}),gt:w(function(a,c,b){for(b=0>b?b+c:b;++b<c;)a.push(b);return a})}};t.pseudos.nth=t.pseudos.eq;for(Q in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[Q]=m(Q);for(Q in{submit:!0,reset:!0})t.pseudos[Q]=h(Q);r.prototype=t.filters=
t.pseudos;t.setFilters=new r;T=c.tokenize=function(a,b){var d,e,g,f,k,m,h;if(k=oa[a+" "])return b?0:k.slice(0);k=a;m=[];for(h=t.preFilter;k;){if(!d||(e=za.exec(k)))e&&(k=k.slice(e[0].length)||k),m.push(g=[]);d=!1;if(e=Aa.exec(k))d=e.shift(),g.push({value:d,type:e[0].replace(Y," ")}),k=k.slice(d.length);for(f in t.filter)if((e=ba[f].exec(k))&&(!h[f]||(e=h[f](e))))d=e.shift(),g.push({value:d,type:f,matches:e}),k=k.slice(d.length);if(!d)break}return b?k.length:k?c.error(a):oa(a,m).slice(0)};fa=c.compile=
function(a,c){var b,d=[],e=[],g=pa[a+" "];if(!g){c||(c=T(a));for(b=c.length;b--;)g=ea(c[b]),g[y]?d.push(g):e.push(g);g=pa(a,va(e,d));g.selector=a}return g};ja=c.select=function(a,c,b,d){var e,g,f,k,m="function"===typeof a&&a,h=!d&&T(a=m.selector||a);b=b||[];if(1===h.length){g=h[0]=h[0].slice(0);if(2<g.length&&"ID"===(f=g[0]).type&&x.getById&&9===c.nodeType&&D&&t.relative[g[1].type]){if(c=(t.find.ID(f.matches[0].replace(F,G),c)||[])[0])m&&(c=c.parentNode);else return b;a=a.slice(g.shift().value.length)}for(e=
ba.needsContext.test(a)?0:g.length;e--;){f=g[e];if(t.relative[k=f.type])break;if(k=t.find[k])if(d=k(f.matches[0].replace(F,G),da.test(g[0].type)&&l(c.parentNode)||c)){g.splice(e,1);a=d.length&&p(g);if(!a)return J.apply(b,d),b;break}}}(m||fa(a,h))(d,c,!D,b,da.test(a)&&l(c.parentNode)||c);return b};x.sortStable=y.split("").sort(ga).join("")===y;x.detectDuplicates=!!R;I();x.sortDetached=g(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});g(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||f("type|href|height|width",function(a,c,b){if(!b)return a.getAttribute(c,"type"===c.toLowerCase()?1:2)});(!x.attributes||!g(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&f("value",function(a,c,b){if(!b&&"input"===a.nodeName.toLowerCase())return a.defaultValue});g(function(a){return null==a.getAttribute("disabled")})||f("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,c,b){var d;if(!b)return!0===a[c]?c.toLowerCase():(d=a.getAttributeNode(c))&&d.specified?d.value:null});"function"===typeof s&&s.amd?s(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie||c.trident,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};b.harmony.DEFAULT=0;b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,c){return this.regexp(c).test(a)},
redact:function(a,c){return a.replace(this.regexp(c),"___")},regexp:function(c){c=b.extend({},c);var e=b.map(b.all(a,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+e.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,c){return this.contains(a+" "+document.referrer,c||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a={NONE:{id:"full",scope:"body",spec:{selector:"body"}},
bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},scope:".post_inner *[id^='body'],.post_inner .signature"},
vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},
c={getPostId:function(a){var c,g;if(this===b.platforms.NONE)return" ";g=this.spec.parse_el?b.select(this.spec.parse_el,a)[0]:a;b.find(this.spec.attributes||["id"],b.bind(function(a){c=g[a]?g[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=[];!a&&(document&&document.body)&&(a=[document.body]);
a&&this.spec&&(c=b.reduce([],b.withScope(a,this.spec.selector),function(a,c){return a.concat(c[1])}));return c}};b.each(a,function(d,e){d.id=d.id||e;b.each(c,function(a,c){d[c]=b.bind(a,d)});a[e]=d});a.DEFAULT_POST_ID=" ";a.findById=function(a){return b.find(b.platforms,function(c){return c.id===a})};return a}();b.observer=function(){var a=[],c=0,d=function(a){c||a.observer.observe(a.context.document,{attributes:!1,characterData:!0,childList:!0,subtree:!0})};return{start:function(c,g){if(c.document&&
b.traits.mutation){var f={context:c,observer:new MutationObserver(b.entryPoint(function(a){var c=[];b.each(a,function(a){var d=[];"characterData"===a.type?a.target&&(d=[a.target]):a.addedNodes&&a.addedNodes.length&&(d=b.toArray(a.addedNodes));d.length&&(c=c.concat(d))});0<c.length&&g(c)}))};a.push(f);d(f)}},pause:function(){c++;b.each(a,function(a){a.observer.disconnect()})},resume:function(){c--;b.each(a,d)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&
void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&!b.browser.ie,quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var h,l,r,p;f={EVENT_LEVEL_LINK:1,EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],
rels:["norewrite"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" ")}),api:function(){var a=function(){var a=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,d){var e=c[d],g;if(e&&e.callback&&a){if("string"===b.type(a)&&(g=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(g[1]);"domains"===d&&"array"===b.type(a)&&(a={results:a});e.callback.apply(window,[a].concat(e.data||[]))}})};return function(d){var k={},m={};b.each(d,
function(a){a=c.apply(this,a);var d=a.method;k[d]=b.prune(a.params);m[d]={callback:a.opts.fn||b.noop,data:a.data}});e({data:m,method:"batch",params:b.extend(f.commonParams(),{batch:window.JSON.stringify(k)}),opts:{jsonp:!1,fn:function(c,b){a(c,b)}}})}}(),c=function(a,c,e){var m=b.toArray(arguments).slice(3,arguments.length),l=a,p=d(e),v;v=b.extend(f.commonParams(a),c);v.subId&&v.key!==h.key&&(v.subId=null);return{data:m,method:l,opts:p,params:v}},d=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=
function(c){return function(d){var e;"object"===b.type(d)&&("array"===b.type(d.crawl)&&"object"===b.type(p.crawler)&&"function"===b.type(p.crawler.crawl))&&(e=b.map(d.crawl,function(a){return a+""}),delete d.crawl,p.crawler.crawl(e));return c.apply(a,arguments)}}(a.fn));return a},e=function(a){return b.request.apply(b,[h.api_url+"/"+a.method,a.params,a.opts].concat(a.data))};return b.batchable(function(){return b.batched(arguments)?a.call(this,b.batchArgs(arguments)):e(c.apply(this,arguments))},function(){return{batch:h.batch_calls,
timeout:h.batch_call_timeout}})}(),addEventListener:function(a,c){this.fire(a,c)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var f=a.open("",c);f.focus();return f}},c=function(a){var c=a.previousSibling,g=a.nextSibling,h=["",a.textContent,""],k=function(a,c){for(var b=a,d=b.data;(b=b[c+"Sibling"])&&3===b.nodeType;)d+=b.data;return d},m=function(a,c,b){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");b=b.replace(/\s+/g,
" ");a=a.replace(/^\s+/,"");" "===c.substr(0,1)&&(c=c.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===c.substr(c.length-1,1)&&(c=c.substr(0,c.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,c,b]};void 0!==h[1]&&(h[0]=c&&3===c.nodeType?k(c,"previous"):"",h[2]=g&&3===g.nodeType?k(g,"next"):"",h=m.apply(this,h),""!==h[0]&&""!==h[2]&&(h[0]=h[0].split(" ").reverse().slice(0,10+(" "===h[0].substr(h[0].length-1,1)?1:0)).reverse().join(" "),h[2]=h[2].split(" ").slice(0,
10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:h[0],after:h[2],txt:h[1],loc:location.href,out:b.getActualHref(a),v:2},f.log("info",b.toQuery(a))))};return function(d,e){var f,q,k,m,l=b.context(d)||window;e=d.target||e;e=!e||e===l.name||"_top"===e&&l.top===l||"_parent"===e&&l.parent===l?"_self":e;k=a(l,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))m="go";else try{if(void 0===k.document)throw!0;m="jsonp"}catch(p){m="go"}f=b.destructing(b.bind(function(){h.time_click&&
arguments.length&&this.logTime("clk");var a=b.toArray(arguments);a.unshift(d,k,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||!h.enabled)return f();q=this.clickParams(d,m);this.logTime();h.log_context&&c(d);if("go"===m)this.redirect(this.api.now("click",q,{"return":!0}),l,k,e);else if(k===l)this.api.now("click",q,{fn:f,timeout:h.click_timeout});else{if(b.contextIsAncestor(l,k))return this.redirect(b.getActualHref(d),
l,k,e);f=b.entryPoint(f);setTimeout(function(){f()},h.click_timeout);k.document.open();k.callback=f;k.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",q,{fn:"callback","return":!0})+'">\x3c/script></head></html>');k.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:h.reaffiliate||null,title:window.document.title,txt:a.innerHTML});
128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:h.key?null:h.dr_key,key:h.key,libId:h.library_id,subId:h.sub_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:h.cuid,loc:location.href,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,c){function b(a,c){0==h||1E3<c?a(0==h&&k):setTimeout(function(){b(a,2*c)},2*c)}function f(){--h||(k=!l&&p)}var k=
!1,h=2,l=!1,p=!1;if("function"==typeof c){a+="?ch=*&rn=*";var r=11*Math.random(),n=new Image;n.onload=f;n.onerror=function(){l=!0;f()};n.src=a.replace(/\*/,1).replace(/\*/,r);n=new Image;n.onload=f;n.onerror=function(){p=!0;f()};n.src=a.replace(/\*/,2).replace(/\*/,r);b(c,250)}}}}catch(c){a={detect:function(a,c){c(!0)}}}return function(c){var e=b.updateUrl(h.asset_url,{pathname:"/images/pixel.gif"});a.detect(e,c)}}(),enabled:function(){if(h.enabled&&r!==window&&window.vglnk&&(window.vglnk.key||"function"===
typeof window.vglnk))h.enabled=!1;return h.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!p[a]){var d=p,e;e=c;e="function"===b.type(e)?b.entryPoint(b.bind(e,f)):e;d[a]=e}}}(),fire:function(){var a={};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,
c){if(h.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":b.cache(a,"href")&&(a.href=b.cache(a,"href"))}},harmony:function(a){return h.harmony_level<=a},init:function(){var a=function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var c=this;
l={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(d){}b.exceptionLogger(b.bind(c.logException,c),!h.dev);b.each(h.script_timeout);return b.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);p=r[n]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&
a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("harmony");this.expose("opt");this.expose("platform");this.expose("registerProcessor",function(){if(0<arguments.length)return f.registerProcessor.apply(f,arguments)});b.extend(p,p===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),
initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;h.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(c){window.DrivingRevenue=void 0}})},initEvents:function(a){var c=b.traits.windowLevelHandlers?a:a.document,d=function(c){c=c||a.event;if((c=b.eventLink(c))&&!b.cache(c,"evented"))q(f.EVENT_LEVEL_LINK,c),b.cache(c,"evented",!0)},e=function(a){b.observer.start(a,b.batchable(function(a){b.batched(arguments)&&
(a=b.reduce([],b.batchArgs(arguments,0),function(a,c){return a.concat(c)}));a=b.all(b.unique(a),function(a){return Boolean(a.parentNode)&&f.allowed(a)});0<a.length&&(b.each(b.withScope(a,"a[href]",{ancestors:!1}),function(a){f.processLinks(a[1])}),b.each(l,function(c,b){f.runPlugin(b,a)}))},function(){return{batch:h.batch_mutation,timeout:h.batch_mutation_timeout}}))},g=function(a,c){return function(){var d=[a].concat(b.toArray(arguments));c.apply(f,d)}},q=function(a,c){b.on(c,"click",g(a,f.onClick));
b.on(c,"contextmenu",g(a,f.onContextmenu))};if(h.dynamic)b.on("DOMReady",function(){e(a)});b.on(c,"copy",b.bind(f.onCopy,f));b.on(c,"mousedown",d);b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",d)})});(!b.traits.quirksMode||f.harmony(b.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&q(f.EVENT_LEVEL_TOP,c)},initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==
window[a]&&(p[c[a]]=window[a],"vglnk_domain"===a&&(p[c[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){h.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(f);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&
(n="vglnk");var a=window,c=n.split("."),b;for(n=c.pop();0<c.length;)b=c.shift(),a[b]=a[b]||{},a=a[b];r=a;p=r[n]=r[n]||{}},initOptions:function(){var a;this.initLegacyOptions();h=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:b.harmony.DEFAULT,link_target:null,rewrite_any:!0,
rewrite_modified:!1,rewrite_original:!0}),h,p,{batch_calls:!0,batch_call_timeout:100,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},script_timeout:2E3,time_click:!1,time_ping:!1,testing_js:[],plugins:{crawler:{},harmony:{},link_affiliation:{},modified_clicks:{}}});for(a in h)"_plugin"===a.substr(-7)&&delete h[a]},initPlugins:function(){var a,c=1,d={link_affiliation:"convert",link_optimization:"optimize",
page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},e=["spotlight"],g=["harmony"],q=function(b){return function(b){return function(){delete l[b].opts.mode;c=1;clearTimeout(a);m()}}(b)},k=function(a){var c;b.find(d,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:h.key,link_phrases:!1});a[c].link_urls=h.link_urls;return a},m=function(){var d={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},e=function(a,
c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,d,a.setup(a.opts,b.clone(b),p,k(h.key))),a["public"]&&f.expose(c,a["public"],!1)),a.opts.mode!==f.PLUGIN_MANUAL&&f.runPlugin(c))},k=function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);f.log.apply(this,c)}}},q=function(a){return!Boolean(a._ran)};a=null;b.each(g,function(a){var c=l[a];c&&!Boolean(c._ran)&&e(c,a)});b.each(b.all(l,q),
e);b.find(l,q)&&(a=setTimeout(b.entryPoint(m),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},r=function(){setTimeout(function(){f.api.flush()},100);m();b.on("DOMReady",function(){setTimeout(f.api.flush,0)})};return function(a){a=k(a);b.each(a,b.bind(function(a,c){c=d[c]||c;"object"===typeof a&&!1!==a.enabled&&(l[c]={opts:a},b.contains(e,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,q(c)))},this));r()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;
c=b.createA(h.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){h.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,
""),a.target="_blank")})},isCommercial:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(h.commercial)&&h.commercial[a]},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["noskim"],custom:function(c){var e=b.canonicalizeHostname(c),g="",l=!1;try{g=c.protocol,e.charAt(0)}catch(k){return!0}l=Boolean(""===e||!g.match(/^https?:$/i)||h.norewrite[e]);if(g=!l)var g=b.cache(c,"type"),m=b.cache(c,"params")||{},g=!Boolean(g||m.type);g&&(l=Boolean(a===
e||!h.rewrite_original||!h.rewrite_any&&!f.isCommercial(c)));return l}});return function(a){return this.allowed(a)&&c(a,{ancestors:!1})}}(),log:function(a,c,d,e){var f,l=b.toQuery({libId:h.library_id,nocache:b.uniqid()});f="pixel.gif";if("custom"===a)l+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(e)?e:[e],function(a){b.each(["e","i","o"],function(c){delete a[c]});l+="&"+b.toQuery(a)});else{l+="&"+b.toQuery({key:h.key,drKey:h.key?null:h.dr_key,subId:h.sub_id});if("time"===a)f="time.gif",
a={time:d,type:c};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;l+="&"+b.toQuery(a)}f=h.api_url+"/"+f+"?"+l;b.pii.transmits(f)||(b.createEl("img").src=f)},logException:function(a){if(h.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},logTime:function(){var a;return function(c){0===arguments.length?a=(new Date).getTime():this.log("time",c,(new Date).getTime()-
a)}}(),onApiClick:function(a,c,d,e,f){var l=e||b.getActualHref(a),k=b.bind(function(){this.redirect(l,b.context(a),c,d)},this);"object"===typeof f&&(f.tracking||f.image)?(e=b.createEl(f.tracking?"iframe":"img",{src:f.tracking||f.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(b.entryPoint(k),f.timeout||h.hop_timeout)):k()},onApiPing:function(a,c,d,e,g,l){h.rewrite_original=!1;g=b.reformatKeys(g||{});var k,m;e=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=
a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};m=b.extend(h.plugins,g.plugins);h=b.extend(h,g);delete h.plugins;h.click_timeout=c;h.library_id=a;h.time_ping&&this.logTime("png");"array"===b.type(h.testing_js)&&0<h.testing_js.length&&b.each(h.testing_js,function(a){b.jsonp(a)});b.extend(h.nofollow,e(l));b.extend(h.norewrite,e(d));for(k in h)"on"===k.toLowerCase().substr(0,2)&&(2<k.length&&"function"===b.type(h[k]))&&(b.on(f,k.toLowerCase().substr(2),b.bind(h[k],window)),delete h[k]);this.initPlugins(m);
this.initContext(window);this.fire("libready")},onClick:function(a,c){c=c||window.event;var d=c.ctrlKey||c.metaKey||c.altKey||c.shiftKey,e=c.which&&1===c.which||0===c.button,f=b.eventLink(c);if(f&&e&&!d&&!b.isDefaultPrevented(c)&&this.isRewritable(f)&&this.shouldHandleClick(a,f))return this.click(f),b.preventDefault(c)},onContextmenu:function(a,c){var d=b.eventLink(c||window.event);d&&(this.isRewritable(d)&&this.shouldHandleClick(a,d))&&this.handleRightClick(d,"setup")},onCopy:function(a){var c,d,
e,g=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{e=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(h){}0<e.length&&128>=e.length&&g.push(e)}}b.each(g,function(a){f.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&(h[a]=c);return h[a]},ping:function(){var a=!1;return function(){if(!a&&(h.key||h.dr_key)){var c={ref:document.referrer||
null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&(h.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(h.platform)||b.platforms.NONE},processLink:function(a){var c=b.cache(a,"processors")||{},d=this.isRewritable(a);b.each(this.registerProcessor(),function(b){!c[b.id]&&(d||b.opts.any)&&b.fn(a);c[b.id]=!0});b.cache(a,
"processors",c);return a},processLinks:function(a){b.each(a,b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,e){c=c||window.top;!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.entryPoint(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,
e),e.rel="norewrite",c.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},runPlugin:function(a,c){var d=window.document,e=l[a];if(e&&e.initDocuments){if(c)e.initNodes(c);else if(e.init(),"function"===b.type(e.initDocuments)&&"document"===b.type(d)&&e.initDocuments([d]),"function"===b.type(e.initNodes)&&"element"===b.type(d.body))b.on("DOMReady",function(){e.initNodes([d.body])});e._ran=!0}},registerProcessor:function(){var a=!1,c=[],d=function(d,f){if(void 0===d)return c;"function"===
b.type(d)&&(f=b.extend({any:!1},f),c.push({fn:d,id:b.uniqid(),opts:f}),a&&this.initLinks())};d(function(){a=!0});return d}(),shouldHandleClick:function(a,c){var d=!0;a===this.EVENT_LEVEL_LINK&&(d=this.harmony(b.harmony.LINK_EVENTS)||this.isCommercial(c)&&this.harmony(b.harmony.COMMERCIAL_LINK_EVENTS));return d}};f.init();try{delete window.vglnk_self}catch(H){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(n,f,b){var s={},h,l;n=f.extend({any:!0},n);l={getDomains:function(){var h=[];f.each(s,function(b,f){2!==s[f]&&(h.push(f),s[f]=2)});0<h.length&&b.api("domains",{domains:h.join("|")},{fn:f.bind(l.onDomainApi,l)})},init:function(){b.opt("link_target",n.link_target);b.opt("rewrite_any",n.any);b.opt("rewrite_original",!0);(h=!n.any||b.harmony(f.harmony.COMMERCIAL_LINK_EVENTS))&&b.registerProcessor(f.bind(function(b){this.initDomainLookup();this.saveDomain(b)},this),
{any:!0})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,f.on("DOMReady",f.bind(this.getDomains,this)))}}(),onDomainApi:function(h){var l;"object"===f.type(h)&&"array"===f.type(h.results)&&(l=b.opt("commercial")||{},f.each(h.results,function(b){l[b]=!0}),b.opt("commercial",l))},saveDomain:function(b){b=f.canonicalizeHostname(b);s[b]=s[b]||1}};return{init:f.bind(l.init,l),initNodes:function(){h&&l.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(n,f,b){var s=[],h=b.platform();n={crawl:function(b){if(h&&!("array"!==f.type(b)||0===b.length))b=f.all(b,function(b){return!f.contains(s,b)}),b=this.findPostsById(b),f.each(b,f.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=f.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return f.all(f.map(h.getPosts(),function(b){return{el:b,id:h.getPostId(b)}}),
function(h){return f.contains(b,h.id)})},processPosts:function(l){l=f.map(l,function(b){s.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:f.toJSON({ct:l,pt:h.id,u:location.href})},{jsonp:!1,ssl:b.opt("dev")?!1:!0})},redact:function(b){return f.pii.redact(b)}};return{"public":{crawl:f.bind(n.crawl,n)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(n,f,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(n,f,b){n=f.extend({key:null},n);var s={init:function(b){f.each(this.getDRSearchForms(b),function(b){if(!f.cache(b,"evented")){var h=s.getInput(b),p=function(){h.value||f.css(h,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};f.cache(b,"evented",!0);b.onsubmit=null;h.onfocus=null;h.onblur=null;f.on(h,"focus",function(){f.css(h,{"background-image":"none"})});f.on(h,"blur",p);p();f.on(b,"submit",function(f){s.onSubmit(f,b)})}})},
getDRSearchForms:function(b){var l=[];f.each(b,function(b){"element"===f.type(b)&&f.each(b.getElementsByTagName("form"),function(b){s.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&l.push(b)})});return l},getInput:function(b){return b.p||b.q2},onSubmit:function(h,l){h=h||window.event;var r="http://shop.ebay.com/i.html?"+f.toQuery({_nkw:s.getInput(l).value}),r=f.createA(r,"_blank");f.cache(r,"params",{key:n.key});b.click(r);return f.preventDefault(h)}};if(n.key)return{init:f.bind(s.init,s),
initNodes:function(b){s.init(b)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(n,f,b){n=f.extend({level:f.harmony.DEFAULT},n);return{init:function(){var f=parseFloat(n.level,10);isFinite(f)&&b.opt("harmony_level",f)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(n,f,b,s){var h,l=b.platform(),r=0;h={cache:function(){var b={};return function(f,a){if(1>=arguments.length){var c;c=f?b[f]:b;return c}if(2===arguments.length)return b[f]=a,!0}}(),getLinks:function(p,n){b.api("optimize",{i:n?n.join("|"):null,pt:l.id,u:location.href},{fn:f.bind(h.onOptimizeApi,h)},p,n)},hasCalled:function(){var b={},h=function(a){return f.isArray(a)&&a.length?Boolean(f.all(a,function(a){return b[a]}).length===a.length):Boolean(b[f.platforms.DEFAULT_POST_ID])},
a=function(a){f.isArray(a)&&a.length?f.each(a,function(a){b[a]=!0}):b[f.platforms.DEFAULT_POST_ID]=!0};return function(c,b){return b?a(c):h(c)}}(),loadOptimizations:function(l,n,a){f.each(l,f.bind(function(a,b){this.cache(b,a)},this));h.hasCalled(a,!0);b.registerProcessor(f.bind(this.optimizeLink,this));this.log()},log:f.batchable(function(){s("optimize",{ct:r});r=0},function(){return{timeout:1E3}}),onOptimizeApi:function(b,h,a){"object"===f.type(b)&&"object"===f.type(b.optLinks)&&this.loadOptimizations(b.optLinks,
h,a)},optimizeLinks:function(b){f.each(f.withScope(b,"a[href]",{ancestors:!1,consolidate:!0}),f.bind(this.optimizeLink,this))},optimizeLink:function(){var b=f.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(a,b){if(b)return Boolean(f.cache(a,"type"))}}),h=function(a){var b=a.href,d=a.textContent||a.innerText,e=Boolean(d),g=function(){var b=f.canonicalizeHostname(a);return RegExp("\\b"+f.escapeRegExp(b)+"\\b","i").test(d)},h=function(){var b=f.canonicalizeHostname(a);
return f.canonicalizeHostname(f.createEl("a",{href:d}))===b},k=function(){var b;return h()?(b=f.fromQuery(a.search),f.find(b,function(a){return a===d})):!1};return{exact:e&&(b===d||function(){var a=d.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+f.map(a,f.escapeRegExp).join(".+")+"$").test(b)}()||k()),partial:e&&(g()||-1!==d.indexOf(b))}};return function(a){var c,d=this.cache(a.href);if(d&&b(a)){c=h(a);if(c.exact){c=d.frdLink||d.optLink;for(var e;e=a.firstChild;)a.removeChild(e);a.appendChild(document.createTextNode(c))}else if(c.partial)return;
f.cache(a,"params",{type:"LO",origOutId:d.pcid+":"+d.linkId});a.href=d.optLink;r++}}}()};return{initNodes:function(b){var n;b=f.nodesOfType(b,1);b.length&&(n=l.getPostIds(b),h.hasCalled(n)?h.optimizeLinks(b):h.getLinks(b,n))}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(n,f,b,s){var h,l,r,p=null,H=null;n=f.extend({cat:null,key:null,link_phrases:!0,link_target:null,link_urls:!0,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},n);if(n.key)return h=b.platform(),l={cache:function(){var a={},b={},d=function(d,e){var h={};f.isArray(e)&&0<e.length&&f.find(e,function(a){if(b[a]){if(d)return h[d]=b[a][d],!0;f.each(b[a],function(a,b){h[b]||(h[b]=a)})}});h=f.extend(f.clone(a),h);return d?h[d]:h},e=function(d,
e,h){(h=f.isArray(h)&&0<h.length?h:null)&&f.each(h,function(a){b[a]=b[a]||{};"L"!==e.type&&(b[a][d]=e)});if(!h||"L"===e.type)a[d]||(a[d]=e);return!0};return function(a,b,c){var h=f.all(f.toArray(arguments),function(a){return Boolean(a)});"array"===f.type(h[h.length-1])&&(c=h.pop());a=h[0];b=h[1];if(1>=h.length)return d(a,c);if(2===h.length)return e(a,b,c)}}(),focusLink:function(a){a.id||(a.id=f.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,
c,d=b.opt("partner"),e={};for(a in d)break;if(a)for(c in d[a])e[a+"_"+c]=d[a][c];return e},getPhrases:function(a,c){b.api("insert",f.extend(l.getPartnerParams(),{cat:n.cat,i:c?c.join("|"):null,mode:n.mode,pt:h.id,ps:n.product_source,u:location.href}),{fn:f.bind(l.onInsertApi,l)},a,c)},hasCalled:function(){var a={},b=function(b){return f.isArray(b)&&b.length?Boolean(f.all(b,function(b){return a[b]}).length===b.length):Boolean(a[f.platforms.DEFAULT_POST_ID])},d=function(b){f.isArray(b)&&b.length?f.each(b,
function(b){a[b]=!0}):a[f.platforms.DEFAULT_POST_ID]=!0};return function(a,f){return f?d(a):b(a)}}(),init:function(){n.scope=n.scope||h.scope;n.link_urls&&(r=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"))},initLink:function(a,c,d){var e=
n.link_target;if(e="U"===c.type?b.opt("link_target"):e||d)a.target=e;a.href||(a.href=c.url);a.rel="nofollow";f.cache(a,"params",{exp:p,key:n.key,mid:c.mid,type:c.type||null});f.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var a,b=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a")&&Boolean(a.href)}}),
d=function(a,f,g,h){if(b(f,{ancestors:!Boolean(h),self:!0}))if(3===f.nodeType)e(a,f,g);else if(1===f.nodeType)for(f=f.firstChild;f;)h=f.nextSibling,d(a,f,g,!0),f=h},e=function(a,b,c){var d=!1,f=b.parentNode,e=function(a,b){f.insertBefore(a,b);f.removeChild(b)};f&&(b.data&&(d=a.test(b.data.replace(/\s+/," "))),d&&g(a,b,c,e))},g=function(b,c,d,e){for(var g,p,r,s,H=function(b){var c;b=!b||!n.per_phrase||!a[b.phrase]||a[b.phrase].count<n.per_phrase;c=!n.per_page||f.reduce(0,a,function(a,b){return a+b.count})<
n.per_page;return b&&c},P=function(a,b,c){var d,e,g;if(!c.phrase)return!0;e=f.createEl("span");b.parentNode.insertBefore(e,b);e.appendChild(b);g=f.geometry(e);(n.proximity||n.same_proximity)&&f.find(l.cache(a),function(a){var b,e;if(a.links){if((b=l.normalizePhrase(a.phrase)===l.normalizePhrase(c.phrase))&&!n.same_proximity||!b&&!n.proximity)return!1;e=b?Math.max(n.same_proximity,n.proximity):n.proximity;a.links=f.all(a.links,function(a){var b=f.isInDom(a.el);!d&&b&&(d=f.find(a.segments,function(a){a=
a.geometry;a=f.extend({},a);a.x1-=e;a.y1-=e;a.x2+=e;a.y2+=e;if(a.x1<g.x2&&a.x2>g.x1&&a.y1<g.y2&&a.y2>g.y1)return!0}));return b});return d}});return function(a){e.parentNode.insertBefore(b,e);e.parentNode.removeChild(e);return a}(!d)},U=function(a,b){var c,d,e,g,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===g||e.offsetTop===g.offsetTop?l.els.push(e):(h.segments.push(l),l={els:[e]}),g=e;l.geometry=f.geometry.apply(f,l.els);h.segments.push(l);
b.links=b.links||[];b.links.push(h);return b};c&&c.data&&""!==c.data&&(Boolean(r=c.data.match(/^\s+/))||Boolean(r=c.data.match(b)));)p=r[0],s=r.slice(1).join(""),g=(g=l.normalizePhrase(s))?l.cache(g,d):null,p=c.data.indexOf(p)+p.length-s.length,0<p&&(c=c.splitText(p)),p=c.length<=s.length?null:c.splitText(s.length),s&&!g&&(g={url:s.match(/^https?:\/\//i)?s:"http://"+s,type:"U"}),g&&(g.url.match(/https?:\/\//i)&&s&&H(g)&&P(d,c,g))&&(s=h(s,g),f.cache(s,"unlinked")||(e(s,c),U(s,g),c=g.phrase||g.url,
a[c]=a[c]||{count:0,phrase:g.phrase,type:g.type},a[c].count++)),c=p},h=function(a,b){var c;c=f.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";f.cache(c,"type","inserted");f.cache(c,"phrase",a);n.ui&&"U"!==b.type&&(c.title="Link added by VigLink");l.initLink(c,b);return c};return function(e,g){var h=l.regexp(g);a={};h&&(f.each(f.all(e,b),function(a){d(h,a,g)}),n.link_phrases&&l.log(a))}}(),loadPhrases:function(a,b,d){f.each(a,function(a){a.phrase&&
a.url&&(a.phrase=l.normalizePhrase(a.phrase),l.cache(a.phrase,{count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},d))});l.hasCalled(d,!0);this.insertLinks(b,d)},log:function(a){var b=0,d=0,e=[];f.each(a,function(a,f){var h=parseInt(a.count,10);0<h&&("U"===a.type?d+=h:e.push({phrase:f,type:a.type,count:h}),b+=h)});0<b&&s("insert",[{ct:b,cl:d,exp:p,imp_id:H,phrases:f.toJSON(e)}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},onInsertApi:function(a,
b,d){"object"===f.type(a)&&(p=a.exp,H=a.imp_id,a.results&&this.loadPhrases(a.results,b,d))},regexp:function(a){var b;a=l.cache(a);a=f.map(a,function(a,b){return f.escapeRegExp(b).split(" ").join("\\s+")});0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(r?"(?:"+b+"|"+r.source+")":b,"i"));return b||r}},{init:f.bind(l.init,l),initNodes:function(a){var b;n.scope&&(a=f.reduce([],f.withScope(a,n.scope),function(a,b){return a.concat(b[1])}));a.length&&(b=h.getPostIds(a),
n.link_phrases&&!l.hasCalled(b)?l.getPhrases(a,b):l.insertLinks(a,b))}}};
